var states = [
	'Alabama',
	'Alaska',
	'Arizona',
	'Arkansas',
	'California',
	'Colorado',
	'Connecticut',
	'Delaware',
	'Florida',
	'Georgia',
	'Hawaii',
	'Idaho',
	'Illinois',
	'Indiana',
	'Iowa',
	'Kansas',
	'Kentucky',
	'Louisiana',
	'Maine',
	'Maryland',
	'Massachusetts',
	'Michigan',
	'Minnesota',
	'Mississippi',
	'Missouri',
	'Montana',
	'Nebraska',
	'Nevada',
	'New Hampshire',
	'New Jersey',
	'New Mexico',
	'New York',
	'North Carolina',
	'North Dakota',
	'Ohio',
	'Oklahoma',
	'Oregon',
	'Pennsylvania',
	'Rhode Island',
	'South Carolina',
	'South Dakota',
	'Tennessee',
	'Texas',
	'Utah',
	'Vermont',
	'Virginia',
	'Washington',
	'West Virginia',
	'Wisconsin',
	'Wyoming'
];

var presidents = [
    'George Washington',
    'John Adams',
    'Thomas Jefferson',
    'James Madison',
    'James Monroe',
    'John Quincy Adams',
    'Andrew Jackson',
    'Martin Van Buren',
    'William Henry Harrison',
    'John Tyler',
    'James Polk',
    'Zachary Taylor',
    'Millard Fillmore',
    'Franklin Pierce',
    'James Buchanan',
    'Abraham Lincoln',
    'Andrew Johnson',
    'Ulysses Grant',
    'Rutherford Hayes',
    'James Garfield',
    'Chester Arthur',
    'Grover Cleveland',
    'Benjamin Harrison',
    'Grover Cleveland',
    'William McKinley',
    'Theodore Roosevelt',
    'William Howard Taft',
    'Woodrow Wilson',
    'Warren Harding',
    'Calvin Coolidge',
    'Herbert Hoover',
    'Franklin Roosevelt',
    'Harry Truman',
    'Dwight Eisenhower',
    'John Kennedy',
    'Lyndon Johnso'n,
    'Richard Nixon',
    'Gerald Ford',
    'James Carte'r,
    'Ronald Reagan',
    'George Bush',
    'William Clinton',
    'George W Bush',
    'Barack Obama'
];

var countries = [
	'Afghanistan',
	'Albania',
	'Algeria',
	'Argentina',
	'Belgium',
	'Belize',
	'Brazil',
	'Bolivia',
	'Canada',
	'Chile',
	'China',
	'Denmark',
	'Dominican Republic',
	'Ecuador',
	'Egypt',
	'Ethiopia',
	'Finland',
	'France',
	'Greece',
	'Guam',
	'Guatemala',
	'Hungary',
	'Iceland',
	'India',
	'Iran',
	'Iraq',
	'Ireland',
	'Israel',
	'Italy',
    'Jamaica',
    'Japan',
	'Kenya',
	'Liberia',
	'Mexico',
	'Mongolia',
	'Morocco',
	'Nepal',
	'Netherlands',
	'New Zealand',
	'Norway',
	'Pakistan',
	'Peru',
	'Philippines',
	'Poland',
	'Portugal',
	'Russia',
	'Singapore',
	'Somalia',
	'South Africa',
	'Spain',
	'Sweden',
	'Taiwan',
	'Turkey',
	'Ukraine',
	'Venezuela',
	'Vietnam',
	'Yemen',
	'Zimbabwe'
];
